/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 raw_assets\Moving_Characters.glb -T -j -M 
Files: raw_assets\Moving_Characters.glb [1.03MB] > C:\Users\andre\My Stuff\VS Code Projects\tutorials\aimees-papercraft-portfolio\Moving_Characters-transformed.glb [121.9KB] (88%)
*/

import { useKTX2Texture } from "../utils/ktxLoader";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCurveProgressStore } from "../../store/useCurveProgressStore";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/Moving_Characters-transformed.glb",
  );

  const texture_1 = useKTX2Texture("/textures/Moving_Characters_1.webp");

  const curves = useCurveProgressStore((state) => state.curves);
  const scrollProgress = useCurveProgressStore((state) => state.scrollProgress);

  const targetLookAt = useRef(new THREE.Vector3(0, 0, 0));
  const upVector = useRef(new THREE.Vector3(0, 1, 0));

  const winterCharacterFrontRef = useRef();
  useFrame(() => {
    if (!winterCharacterFrontRef.current) return;

    const point = curves.movingCharactersCurve.getPointAt(scrollProgress);
    const tangent = curves.movingCharactersCurve.getTangentAt(scrollProgress);

    winterCharacterFrontRef.current.position.copy(point);

    targetLookAt.current.crossVectors(tangent, upVector.current);

    winterCharacterFrontRef.current.lookAt(targetLookAt.current);
  });

  return (
    <group {...props} dispose={null}>
      <group ref={winterCharacterFrontRef}>
        <mesh
          geometry={nodes.Moving_Characters_Winter_arm_left_front.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_arm_left_front.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_arm_right_front.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_arm_right_front.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_front_character.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_front_character.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_Front_Smile.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_Front_Smile.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_front_smile_face.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_front_smile_face.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_happy_face.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_happy_face.position}
        />
        <mesh
          geometry={nodes.Moving_Characters_Winter_head_front.geometry}
          material={texture_1}
          position={nodes.Moving_Characters_Winter_head_front.position}
        />
      </group>

      <mesh
        geometry={nodes.Moving_Characters_Winter_left_arm.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Winter_left_arm.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_right_arm.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Winter_right_arm.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_left_foot.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Winter_left_foot.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_right_foot.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Winter_right_foot.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Winter_side.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Winter_side.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Spring_front.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Spring_front.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Spring_side.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Spring_side.position}
        rotation={nodes.Moving_Characters_Spring_side.rotation}
        scale={nodes.Moving_Characters_Spring_side.scale}
      />
      <mesh
        geometry={nodes.Moving_Characters_Spring_side_back_wheel.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Spring_side_back_wheel.position}
        rotation={nodes.Moving_Characters_Spring_side_back_wheel.rotation}
        scale={nodes.Moving_Characters_Spring_side_back_wheel.scale}
      />
      <mesh
        geometry={nodes.Moving_Characters_Spring_side_front_wheel.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Spring_side_front_wheel.position}
        rotation={nodes.Moving_Characters_Spring_side_front_wheel.rotation}
        scale={nodes.Moving_Characters_Spring_side_front_wheel.scale}
      />
      <mesh
        geometry={nodes.Moving_Characters_Fall_character.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Fall_character.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Fall_face.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Fall_face.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Fall_left_arm.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Fall_left_arm.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Fall_right_arm.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Fall_right_arm.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Summer_character.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Summer_character.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Summer_character_Wave.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Summer_character_Wave.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Summer_happy_face.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Summer_happy_face.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Summer_left_arm.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Summer_left_arm.position}
      />
      <mesh
        geometry={nodes.Moving_Characters_Summer_right_arm.geometry}
        material={texture_1}
        position={nodes.Moving_Characters_Summer_right_arm.position}
      />
    </group>
  );
}

useGLTF.preload("/models/Moving_Characters-transformed.glb");
